version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bgj3kr8pq3rf"
s3_prefix = "s3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
