package com.gradadmissionshub.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Collection;
import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "Applicants")
public class Applicant {

    private String id;
    private String name;
    private Date graduationDate;
    private List<String> majors;

    public Applicant(String name, Date graduationDate, List<String> majors) {
        this.name = name;
        this.graduationDate = graduationDate;
        this.majors = majors;
    }

    public Applicant() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public Date getGraduationDate() {
        return graduationDate;
    }

    @DynamoDBAttribute
    public List<String> getMajors() {
        return majors;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setGraduationDate(Date date) {
        graduationDate = date;
    }

    public void setMajors(List<String> majors) {
        this.majors = majors;
    }
}
