package com.gradadmissionshub.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;
import java.util.Date;

@DynamoDBTable(tableName = "Applications")
public class Application {

    private String id;
    private String applicantId;
    private String professorId;
    private Date dateSubmitted;
    private List<String> areasOfResearch;
    private String resumeDocumentId;
    private String diplomaDocumentId;
    private String auditDocumentId;
    private List<String> reviewIds;

    public Application(String applicantId, String professorId, Date dateSubmitted, List<String> areasOfResearch) {
        this.applicantId = applicantId;
        this.professorId = professorId;
        this.dateSubmitted = dateSubmitted;
        this.areasOfResearch = areasOfResearch;
    }

    public Application() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getApplicantId() {
        return applicantId;
    }

    @DynamoDBAttribute
    public String getProfessorId() {
        return professorId;
    }

    @DynamoDBAttribute
    public Date getDateSubmitted() {
        return dateSubmitted;
    }

    @DynamoDBAttribute
    public List<String> getAreasOfResearch() {
        return areasOfResearch;
    }

    @DynamoDBAttribute
    public String getResumeDocumentId() {
        return resumeDocumentId;
    }

    @DynamoDBAttribute
    public String getDiplomaDocumentId() {
        return diplomaDocumentId;
    }

    @DynamoDBAttribute
    public String getAuditDocumentId() {
        return auditDocumentId;
    }

    @DynamoDBAttribute
    public List<String> getReviewIds() {
        return reviewIds;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    public void setDateSubmitted(Date dateSubmitted) {
        this.dateSubmitted = dateSubmitted;
    }

    public void setAreasOfResearch(List<String> areasOfResearch) {
        this.areasOfResearch = areasOfResearch;
    }

    public void setResumeDocumentId(String resumeDocumentId) {
        this.resumeDocumentId = resumeDocumentId;
    }

    public void setDiplomaDocumentId(String diplomaDocumentId) {
        this.diplomaDocumentId = diplomaDocumentId;
    }

    public void setAuditDocumentId(String auditDocumentId) {
        this.auditDocumentId = auditDocumentId;
    }

    public void setReviewIds(List<String> reviewIds) {
        this.reviewIds = reviewIds;
    }
}
