package com.gradadmissionshub.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "Professors")
public class Professor {

    private String id;
    private String name;
    private List<String> areasOfResearch;

    public Professor(String id, String name, List<String> areasOfResearch) {
        this.id = id;
        this.name = name;
        this.areasOfResearch = areasOfResearch;
    }

    public Professor() {}

    @DynamoDBHashKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    @DynamoDBAttribute
    public List<String> getAreasOfResearch() {
        return areasOfResearch;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAreasOfResearch(List<String> areasOfResearch) {
        this.areasOfResearch = areasOfResearch;
    }
}
